### ISSUE TITLE
Normal Vote

### ISSUE THREAD

**Issue by onnnnnnnion** [wilsoncusack/voter.wtf#21]
independent of the "mint vote" idea, enable onchain voting on the nounsvote.wtf client - could enforce that they have to add a reason with n minimum characters :)

**Comment by wilsoncusack** [comment]
yes want to do this, thanks @onnnnnnnion ! Thoughts @ethandaya ?

**Comment by wilsoncusack** [comment]
@onnnnnnnion one thing I'd like to have is a sort of re-vote-with reason. Vote with a quote of someone else's vote

**Comment by wilsoncusack** [comment]
Thinking we should have heroicon write icon, like a tweet button, up by connect wallet after you've connected. Pressing this show show a modal. There's a dropdown picker of the prop you want to vote on it. It should include all active props, minus what you've already voted on. Anyone can vote, not just nouns voter. Probably should show how many votes they're voting with? But we'd need to query snapshot for that. Want to make sure it has plenty of space on screen for long vote reasons, by default it should end with *voted with voter.wtf* or maybe *sent from voter.wtf*. On mobile probably take over whole screen like a tweet

**Comment by wilsoncusack** [comment]
Should useContractWrite from Wagmi. Will need to use wagmi generate to get a ts abi
